apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels: {}
  annotations: {}
spec:
  strategy:
    type: Recreate
    # type: RollingUpdate
    # rollingUpdate:
    #   maxUnavailable: 23%
    #   maxSurge: 25%
  replicas: 3
  selector:
    matchLabels:         
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
        - name: nginx
          image: nginx:1.28
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          env:
          - name: APPLICATION_ENVIRONMENT
            value: staging
      restartPolicy: Always